apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.targetPort }}
      nodePort: {{ .Values.backend.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          image: smart-forms-backend:latest
          command: ["uvicorn", "backend.API.main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL }}
            - name: FRONTEND_BASE_URL
              value: "{{ .Values.env.MINIKUBE_IP }}:{{ .Values.frontend.nodePort }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
