apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.targetPort }}
      nodePort: {{ .Values.frontend.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          image: {{ .Values.frontend.imageName }}:{{ .Values.image.tag }}
          command: ["npm", "run", "dev"]
          env:
            - name: VITE_BACKEND_BASE_URL  # The name has to be prefixed with 'VITE' to be sent to client-side
              value: "{{ .Values.env.MINIKUBE_IP }}:{{ .Values.backend.nodePort }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
