apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          imagePullPolicy: IfNotPresent
          image: smart-forms-backend:latest
          command: ["uvicorn", "backend.API.main:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@database:5432/smart-forms"
            - name: FRONTEND_BASE_URL
              value: "http://192.168.64.2:30547"
          ports:
            - containerPort: 8000
