"""add owner

Revision ID: 21a63d64113e
Revises: 79022452b457
Create Date: 2023-09-03 15:16:42.439590

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '21a63d64113e'
down_revision = '79022452b457'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'owner')
    # ### end Alembic commands ###